### ISSUE TITLE
Support babel-options

### ISSUE THREAD

**Issue by waywaaard** [cramforce/splittable#15]
I could not find a way to pass in specific babel options for transpiling jsx (in `.js`) files and to add some other presets.

**Comment by dobbym** [comment]
Can't you specify these in a .babelrc file?

**Comment by cramforce** [comment]
You can, but currently the babel output is ignored. I'm thinking about
changing that. You'd only want to do it for stuff not supported by closure
compiler, though (such as JSX), for best results

On Nov 21, 2016 11:58 AM, "David Merrilees" <notifications@github.com>
wrote:

Can't you specify these in a .babelrc file?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cramforce/splittable/issues/15#issuecomment-262049667>,
or mute the thread

**Comment by cramforce** [comment]
See #31

**Comment by cramforce** [comment]
JSX is now supported.

**Comment by waywaaard** [comment]
Thanks
